const LOGIN_SAGA = 'LOGIN_SAGA';
const LOGIN_FAIL = 'LOGIN_FAIL';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

const LOGOUT_SAGA = 'LOGOUT_SAGA';

const CREATE_NEW_USER_SAGA = 'CREATE_NEW_USER_SAGA';
const CREATE_NEW_USER_SUCCESS = 'CREATE_NEW_USER_SUCCESS';
const CREATE_NEW_USER_FAIL = 'CREATE_NEW_USER_FAIL';

const CREATE_QUIZ_SAGA = 'CREATE_QUIZ_SAGA';
const CREATE_QUIZ_SUCCESS = 'CREATE_QUIZ_SUCCESS';
const CREATE_QUIZ_FAIL = 'CREATE_QUIZ_FAIL';

const GET_WHOAMI_SAGA = 'GET_WHOAMI_SAGA';
const GET_WHOAMI_SUCCESS = 'GET_WHOAMI_SUCCESS';
const GET_WHOAMI_FAIL = 'GET_WHOAMI_FAIL';

const CLEAR_WHOAMI = 'CLEAR_WHOAMI';

const CHANGE_PASSWORD_SAGA = 'CHANGE_PASSWORD_SAGA';

export {
  LOGIN_SAGA,
  LOGIN_FAIL,
  LOGIN_SUCCESS,

  CREATE_NEW_USER_SAGA,
  CREATE_NEW_USER_SUCCESS,
  CREATE_NEW_USER_FAIL,

  CREATE_QUIZ_SAGA,
  CREATE_QUIZ_SUCCESS,
  CREATE_QUIZ_FAIL,

  LOGOUT_SAGA,

  GET_WHOAMI_SAGA,
  GET_WHOAMI_SUCCESS,
  GET_WHOAMI_FAIL,

  CLEAR_WHOAMI,

  CHANGE_PASSWORD_SAGA,
};
