const LOGIN_SAGA = 'LOGIN_SAGA';
const LOGIN_FAIL = 'LOGIN_FAIL';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

const LOGOUT_SAGA = 'LOGOUT_SAGA';

const GET_WHOAMI_SAGA = 'GET_WHOAMI_SAGA';
const GET_WHOAMI_SUCCESS = 'GET_WHOAMI_SUCCESS';
const GET_WHOAMI_FAIL = 'GET_WHOAMI_FAIL';

const SET_WHOAMI_SAGA = 'SET_WHOAMI_SAGA';
const SET_WHOAMI_SUCCESS = 'SET_WHOAMI_SUCCESS';
const SET_WHOAMI_FAIL = 'SET_WHOAMI_FAIL';

const CLEAR_WHOAMI = 'CLEAR_WHOAMI';

export {
  LOGIN_SAGA,
  LOGIN_FAIL,
  LOGIN_SUCCESS,

  LOGOUT_SAGA,

  GET_WHOAMI_SAGA,
  GET_WHOAMI_SUCCESS,
  GET_WHOAMI_FAIL,

  SET_WHOAMI_SAGA,
  SET_WHOAMI_SUCCESS,
  SET_WHOAMI_FAIL,

  CLEAR_WHOAMI,
};
